# analysis_options.yaml

analyzer:
  errors:
    todo: ignore
  exclude:
    - lib/firebase_options.dart

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - sort_child_properties_last
    - unawaited_futures
