// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBloVJ3SYbQ_iQYLkMmvPbuWYv8HloUdS8',
    appId: '1:1082893682446:web:bd159e6f551986cb56f95f',
    messagingSenderId: '1082893682446',
    projectId: 'fir-crud-basics-5fd25',
    authDomain: 'fir-crud-basics-5fd25.firebaseapp.com',
    storageBucket: 'fir-crud-basics-5fd25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQUsfb8B4Rngf69n_wG6ygL-S2raF_f4c',
    appId: '1:1082893682446:android:11396601a2653c2d56f95f',
    messagingSenderId: '1082893682446',
    projectId: 'fir-crud-basics-5fd25',
    storageBucket: 'fir-crud-basics-5fd25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk8LWTMTrABZP87S6OBA8k0LTdkBKvINU',
    appId: '1:1082893682446:ios:a3abafc6ec8fad9c56f95f',
    messagingSenderId: '1082893682446',
    projectId: 'fir-crud-basics-5fd25',
    storageBucket: 'fir-crud-basics-5fd25.firebasestorage.app',
    iosBundleId: 'com.naswan.safereceipt.safeReceipt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk8LWTMTrABZP87S6OBA8k0LTdkBKvINU',
    appId: '1:1082893682446:ios:a3abafc6ec8fad9c56f95f',
    messagingSenderId: '1082893682446',
    projectId: 'fir-crud-basics-5fd25',
    storageBucket: 'fir-crud-basics-5fd25.firebasestorage.app',
    iosBundleId: 'com.naswan.safereceipt.safeReceipt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBloVJ3SYbQ_iQYLkMmvPbuWYv8HloUdS8',
    appId: '1:1082893682446:web:e849a367f89e0f3156f95f',
    messagingSenderId: '1082893682446',
    projectId: 'fir-crud-basics-5fd25',
    authDomain: 'fir-crud-basics-5fd25.firebaseapp.com',
    storageBucket: 'fir-crud-basics-5fd25.firebasestorage.app',
  );
}
